---
- hosts: all
  remote_user: test
  vars:
    srcdir: /home/test/src/prelude
  tasks:
    - name: Make source directory
      command:
        cmd: mkdir -p "{{srcdir}}"
    - name: Copy source
      synchronize:
        # Why do we need to go up 2 directories here? Bug in syncronize module?
        src: ../../
        dest: "{{srcdir}}"
        rsync_opts:
          - "--exclude=.git"
    - name: Clean
      command:
        chdir: "{{srcdir}}"
        cmd: make clean
    - name: Prepare
      command:
        chdir: "{{srcdir}}"
        cmd: ./configure
    - name: Build
      command:
        chdir: "{{srcdir}}"
        cmd: make
    - name: Execute
      command:
        chdir: "{{srcdir}}"
        cmd: ./prelude
